services:
  retrodigger-api:
    container_name: retrodigger-api
    build:
      context: .
      dockerfile: Server.RetroDigger/Dockerfile
    ports:
      - "6875:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SCORES_PATH: /data/scores.json
    volumes:
      - ./data:/data
    restart: unless-stopped
